import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  title: 'Stock Management System - CodeWithHarry',
  description: 'Generated by create next app',
}